apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  # - name: Local Accounts
  #   mappingMethod: claim
  #   type: HTPasswd
  #   htpasswd:
  #     fileData:
  #       name: htpasswd
  - name: AUTH-TITLE
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "uid=${BINDUSER},cn=users,cn=accounts,dc=${DOMAIN},dc=${COM}"
      bindPassword:
        name: ldap-secret
      insecure: false
      ca:
        name: ca-configmap
      url: "ldaps://${LDAPSVR}.${DOMAIN}.${COM}:636/cn=users,cn=accounts,dc=${DOMAIN},dc=${COM}?uid"
