kind: LDAPSyncConfig
apiVersion: v1
url: "ldaps://${LDAPSVR}.${DOMAIN}.${COM}:636"
bindDN: "uid=${BINDUSER},cn=users,cn=accounts,dc=${DOMAIN},dc=${COM}"
bindPassword:
  name: ldap-secret 
ca:
  name: ca-configmap
insecure: false
rfc2307:
  groupsQuery:
    baseDN: "cn=groups,cn=accounts,dc=${DOMAIN},dc=${COM}"
    scope: sub
    derefAliases: never
    filter: (objectClass=groupofnames)
    pageSize: 0
    timeout: 0
  groupUIDAttribute: dn
  groupNameAttributes: [ cn ]
  groupMembershipAttributes: [ member ]
  usersQuery:
    baseDN: "cn=users,cn=accounts,dc=${DOMAIN},dc=${COM}"
    scope: sub
    derefAliases: never
    pageSize: 0
  userUIDAttribute: dn
  userNameAttributes: [ uid ]